version: 2
# Row data. Sources : Staging models = 1:1
sources:
  - name: snowflake
    description: "Clone of marketing data from Google Analytics in Snowflake"
    database: fivetran_database
    schema: google_sheets  
    tables:
      - name: raw_campaigns
        columns:
        - name: campaing_id
          tests:
            - not_null
      - name: raw_customers
        columns:
          - name: cust_id
            tests:
            - not_null
       
        # Freshness: the acceptable amount of time between the most recent record and now
        loaded_at_field: _fivetran_synced
        freshness:
          warn_after: {count: 12, period: hour}
          error_after: {count: 24, period: hour}
